name: fvp
description: video_player plugin and APIs for your own players. Support all desktop/mobile platforms. Hardware decoders, optimal renders. Supports most formats via FFmpeg
version: 0.13.1
homepage: https://github.com/wang-bin/fvp
topics:
  - video
  - player
  - video-player
  - audio-player
  - cross-platform

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  ffi: ^2.1.0
  flutter:
    sdk: flutter
  logging: ^1.2.0
  path: ^1.8.3
  plugin_platform_interface: ^2.1.7
  html: ^0.15.0
  meta: ^1.3.0
  async: ^2.11.0





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  ffigen: ^10.0.0
  lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.mediadevkit.fvp
        pluginClass: FvpPlugin
      ios:
        pluginClass: FvpPlugin
        sharedDarwinSource: true
      linux:
        pluginClass: FvpPlugin
      macos:
        pluginClass: FvpPlugin
        sharedDarwinSource: true
      windows:
        pluginClass: FvpPluginCApi
